spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3307/user_service_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123qwe

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

