version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: msa-zipkin
    ports:
      - "9411:9411"
    networks:
      - msa-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: msa_rabbitmq
    ports:
      - "5672:5672" # AMQP 포트
      - "15672:15672" # UI 포트
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - msa-network

  mysql:
    image: mysql:8.0
    container_name: msa-mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    restart: always
    networks:
      - msa-network

volumes:
  mysql-data:

networks:
  msa-network:
    name: msa-network
    driver: bridge
