spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.sesac: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

info:
  environment: "Development"
  debug: true
